Repository 20th-lion/camperz, pull requests merged in 2022-12, with the labels that each got.

#9 Feat/myprofile
  src/component/common/Button.js
  src/component/common/Header.js
  src/component/common/NavBar.js
  src/component/user/UserProfile.js
  src/lib/apis/customAxios.js
  src/lib/apis/profileApis.js
  src/pages/Profile/ProfilePage.js
Labels: feat

#7 Feat/Myprofile
  src/App.js
  src/apis/postApis.js
  src/post/PostItem.js
  src/post/PostList.js
Labels: feat

#15 Feat/myproduct
  src/App.js
  src/component/post/PostItem.js
  src/component/product/ProductItem.js
  src/component/product/ProductList.js
  src/lib/apis/productApis.js
  src/lib/styles/palette.js
  src/pages/Profile/ProfilePage.js
Labels: feat

#17 refactor: splash에서 테스트코드 주석 삭제
  src/pages/Home/Splash.js
Labels: refactor

#19 refactor: splash에서 테스트코드 주석 삭제
  src/pages/Home/Splash.js
Labels: refactor

#25 Feat/postupload
  src/component/common/ImgUploadButton.js
  src/component/common/NavBar.js
  src/component/post/UploadButton.js
  src/lib/apis/customAxios.js
  src/lib/apis/imageUploadApi.js
  src/lib/apis/postUploadApis.js
  src/pages/PostUploadPage.js
  src/post/PostUploadPage.js
Labels: feat

#27 Feat/modal
  src/App.js
  src/component/context/ModalsContext.js
  src/component/context/Provider.js
Labels: feat, refactor

#30 refactor: splash refactoring
  src/pages/Home/Splash.js
Labels: refactor

#31 feat: loginPage
  src/pages/Login/LoginPage.js
Labels: feat

#29 Feat/mypost
  src/App.js
  src/component/common/Button.js
  src/component/post/HeartBtton.js
  src/component/post/PostItem.js
  src/component/post/PostList.js
  src/lib/apis/HeartApis.js
  src/lib/styles/palette.js
  src/pages/Profile/ProfilePage.js
  src/pages/folow/FollowPage.js
Labels: feat, refactor

#34 Feat/editprofile
  src/component/form/ProfileForm.js
  src/lib/apis/profileApis.js
  src/pages/Profile/ProfileEditPage.js
Labels: feat

#38 Feat/productedit
  src/App.js
  src/component/form/ProductForm.js
  src/lib/apis/productApis.js
  src/pages/Product/ProductEditPage.js
  src/pages/Product/ProductUploadPage.js
Labels: feat, refactor

#40 Feat/profile
  src/App.js
  src/component/common/BackButton.js
  src/component/common/Header.js
  src/component/form/ProfileForm.js
  src/component/post/PostList.js
  src/component/product/ProductList.js
  src/component/user/UserProfile.js
  src/lib/apis/postApis.js
  src/lib/apis/productApis.js
  src/pages/Product/ProductEditPage.js
  src/pages/Product/ProductUploadPage.js
  src/pages/Profile/ProfileEditPage.js
  src/pages/Profile/ProfilePage.js
Labels: feat, refactor

#43 feat/ 포스트 이미지만 볼수 있는 버튼
  src/component/post/PostItem.js
  src/component/post/PostList.js
  src/component/post/PostPicture.js
Labels: feat

#50 Feat/follow
  src/App.js
  src/component/common/Button.js
  src/component/follow/FollowButton.js
  src/component/follow/FollowContents.js
  src/component/follow/FollowUser.js
  src/component/post/PostItem.js
  src/component/post/PostList.js
  src/lib/apis/followApis.js
  src/pages/Profile/ProfilePage.js
  src/pages/follow/FollowPage.js
  src/pages/folow/FollowPage.js
Labels: feat

#53 refactor/ 이미지 저장방식 변경
  src/component/form/ProfileForm.js
  src/pages/Profile/ProfileEditPage.js
Labels: refactor

#52 Refactor/productedit
  src/component/form/ProductForm.js
  src/pages/Product/ProductEditPage.js
Labels: refactor

#48 Feat/modal
  src/component/context/Provider.js
  src/component/modal/ConfirmModal.js
  src/component/modal/Modals.js
  src/component/modal/ProductModal.js
  src/component/modal/ProfileModal.js
Labels: feat

#55 Feat/postdetailpage
  src/App.js
  src/assets/image/commentbtn.svg
  src/component/common/Button.js
  src/component/common/CommentBox.js
  src/component/post/PostDetailComment.js
  src/component/post/PostDetailContent.js
  src/lib/apis/commentApis.js
  src/lib/apis/postApis.js
  src/lib/styles/palette.js
  src/pages/post/PostDetailPage.js
Labels: feat

#56 Feat/login+register
  src/component/form/AuthForm.js
  src/lib/apis/client.js
  src/lib/apis/loginApis.js
  src/lib/apis/registerApis.js
  src/lib/utils/isLogin.js
  src/lib/utils/isValidToken.js
  src/pages/Home/Splash.js
  src/pages/Login/LoginByEmail.js
  src/pages/Login/LoginPage.js
  src/pages/Register/Register.js
Labels: feat

#62 HomePage 더미 페이지 업로드
  src/pages/Home/HomePage.js
Labels: fix

#60 Refactor/usehook
  src/App.js
  src/component/post/PostDetailComment.js
  src/component/post/PostItem.js
  src/pages/post/PostDetailPage.js
Labels: refactor

#64 Refactor/postdetail
  src/component/post/CommentItem.js
  src/component/post/PostDetailComment.js
  src/component/post/PostDetailContent.js
  src/component/post/PostItem.js
  src/lib/apis/commentApis.js
  src/lib/apis/postApis.js
  src/pages/post/PostDetailPage.js
Labels: feat, fix, refactor

#65 Feat/chatpage
  src/App.js
  src/assets/image/camp.jpg
  src/assets/image/chat-profile.svg
  src/assets/image/plus-button.svg
  src/component/chat/ChatItem.js
  src/component/chat/ChatList.js
  src/component/common/CommentBox.js
  src/component/common/NavBar.js
  src/component/post/PostDetailComment.js
  src/lib/dummy/chatdata.js
  src/lib/styles/palette.js
  src/pages/Chat/ChatListPage.js
  src/pages/Chat/ChatRoomPage.js
Labels: feat

#68 feat: register 페이지 완성
  src/assets/image/CAMPERZ-logo-dark.svg
  src/assets/image/CAMPERZ-logo-light.svg
  src/assets/image/default-profile-img.svg
  src/component/form/ProfileForm.js
  src/lib/apis/registerApis.js
  src/lib/utils/profileValidation.js
  src/pages/Login/LoginByEmail.js
  src/pages/Login/LoginPage.js
  src/pages/Register/Register.js
Labels: feat

#67 Feat/following
  src/App.js
  src/component/follow/FollowButton.js
  src/component/follow/FollowContents.js
  src/component/follow/FollowUser.js
  src/component/post/PostItem.js
  src/component/user/UserProfile.js
  src/lib/apis/customAxios.js
  src/lib/apis/registerApis.js
  src/pages/Profile/ProfilePage.js
  src/pages/follow/FollowerPage.js
  src/pages/follow/FollowingPage.js
Labels: feat

#70 fix: homepage import code 추가
  src/App.js
Labels: fix

#75 fix/경로 오류 수정
  src/component/post/PostItem.js
Labels: fix

#78 fix: 경로+임포트수정
  src/App.js
  src/component/common/ModalButton.js
  src/component/form/ProfileForm.js
  src/lib/apis/registerApis.js
  src/lib/utils/profileValidation.js
  src/pages/Login/LoginPage.js
Labels: fix

#79 Fix/경로+임포트수정
  src/pages/Follow/FollowerPage.js
  src/pages/Follow/FollowingPage.js
  src/pages/Post/PostDetailPage.js
  src/pages/Post/PostUploadPage.js
Labels: fix

#80 feat: accountnameValid 오류 수정
  src/component/form/ProfileForm.js
  src/lib/utils/profileValidation.js
Labels: fix

#74 fix: 상품 이미지 업로드 오류 수정
  src/component/form/ProductForm.js
  src/pages/Product/ProductEditPage.js
  src/pages/Product/ProductUploadPage.js
Labels: fix

#82 Fix/userinfo
  src/App.js
  src/component/form/ProductForm.js
  src/component/form/ProfileForm.js
  src/component/user/UserProfile.js
  src/lib/apis/imageUploadApi.js
  src/lib/apis/registerApis.js
  src/pages/Follow/FollowerPage.js
  src/pages/Follow/FollowingPage.js
  src/pages/Product/ProductEditPage.js
  src/pages/Product/ProductUploadPage.js
  src/pages/Profile/ProfileEditPage.js
  src/pages/Profile/ProfilePage.js
  src/pages/Register/Register.js
Labels: feat, fix

#84 docs: resetCss
  package-lock.json
  package.json
Labels: docs

#87 feat: 프로필페이지에서 포스트 모달 구현
  src/component/modal/Modals.js
  src/component/modal/PostItemModal.js
  src/component/post/PostItem.js
  src/component/post/PostList.js
  src/lib/apis/postApis.js
  src/pages/Profile/ProfilePage.js
Labels: feat

#88 Feat/global css
  public/index.html
  src/App.js
  src/lib/styles/GlobalStyle.js
Labels: feat

#90 style: assets 추가
  src/App.js
  src/assets/icons/404_logo.png
  src/assets/icons/Facebook_Logo.png
  src/assets/icons/Google_Logo.png
  src/assets/icons/Kakao_Logo.png
  src/assets/icons/basic_profile.png
  src/assets/icons/basic_profile_chat.png
  src/assets/icons/basic_profile_post.png
  src/assets/icons/chat_send.png
  src/assets/icons/chat_upload.png
  src/assets/icons/heart.png
  src/assets/icons/heart_fill.png
  src/assets/icons/home.png
  src/assets/icons/home_fill.png
  src/assets/icons/icon_arrow_left.png
  src/assets/icons/icon_search.png
  src/assets/icons/img_layers.png
  src/assets/icons/img_upload_post.png
  src/assets/icons/img_upload_profile.png
  src/assets/icons/message.png
  src/assets/icons/message_fill.png
  src/assets/icons/more_header.png
  src/assets/icons/more_post.png
  src/assets/icons/post.png
  src/assets/icons/post_album.png
  src/assets/icons/post_album_fill.png
  src/assets/icons/post_fill.png
  src/assets/icons/post_list.png
  src/assets/icons/post_list_fill.png
  src/assets/icons/reple.png
  src/assets/icons/user.png
  src/assets/icons/user_fill.png
  src/assets/icons/x.png
  src/assets/icons/yourProfile_chat.png.png
  src/assets/icons/yourProfile_share.png
  src/assets/image/404logo.svg
  src/assets/image/CAMPERZ-logo-dark.svg
  src/assets/image/CAMPERZ-logo-light.svg
  src/assets/image/chat-profile.svg
  src/assets/image/commentbtn.svg
  src/assets/image/default-profile-img.svg
  src/assets/image/img-upload-icon.svg
  src/assets/image/plus-button.svg
  src/assets/logo/CAMPERZ_dark.png
  src/assets/logo/CAMPERZ_light.png
  src/component/common/CommentBox.js
  src/component/common/Header.js
  src/component/common/ImgUploadButton.js
  src/component/form/ProductForm.js
  src/component/form/ProfileForm.js
  src/component/post/PostDetailComment.js
  src/lib/dummy/chatdata.js
  src/pages/Chat/ChatRoomPage.js
  src/pages/ErrorPage/Page404.js
  src/pages/Home/HomePage.js
Labels: style

#91 Postedit
  src/App.js
  src/component/post/PostDetailContent.js
  src/component/post/UploadButton.js
  src/lib/apis/postApis.js
  src/pages/Post/PostDetailPage.js
  src/pages/Post/PostUploadPage.js
Labels: feat

#92 Fix/postbug
  src/App.js
  src/component/post/PostDetailContent.js
  src/component/post/PostItem.js
  src/lib/apis/postApis.js
Labels: feat, fix

#93 Feat/feed
  src/component/common/NavBar.js
  src/component/common/SearchBtn.js
  src/component/feed/Feed.js
  src/component/form/ProfileForm.js
  src/component/post/PostItem.js
  src/component/post/PostList.js
  src/component/user/UserProfile.js
  src/lib/apis/postApis.js
  src/pages/Home/HomePage.js
  src/pages/Profile/ProfileEditPage.js
  src/pages/Profile/ProfilePage.js
Labels: feat

#95 fix: 경로수정
  src/pages/Profile/ProfileEditPage.js
Labels: fix

#96 feat: common styles 적용
  src/component/common/Header.js
  src/component/common/NavBar.js
  src/component/common/SearchButton.js
  src/component/feed/Feed.js
  src/lib/styles/GlobalStyle.js
  src/pages/ErrorPage/Page404.js
  src/pages/Home/HomePage.js
Labels: feat

#97 feat: common Style
  src/App.js
  src/component/feed/Feed.js
  src/lib/styles/GlobalStyle.js
  src/pages/Home/HomePage.js
Labels: feat

#98 fix: profile 경로 수정
  src/pages/Profile/ProfilePage.js
Labels: fix

#99 fix: 팔로워수 실시간 변화
  src/component/common/Header.js
  src/component/user/UserProfile.js
  src/pages/Follow/FollowingPage.js
Labels: fix

#106 fix: 프로필 페이지 렌더링 오류 해결
  src/component/post/PostList.js
  src/component/product/ProductList.js
  src/component/user/UserProfile.js
  src/pages/Profile/ProfilePage.js
Labels: fix

#103 Feat/common
  public/favicon.ico
  public/favicon.png
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/component/common/ButtonBig.js
  src/component/common/ButtonRectangle.js
  src/component/common/ButtonSmall.js
  src/component/common/NavBar.js
Labels: feat

#107 style: post item 스타일 작업
  src/component/post/HeartBtton.js
  src/component/post/PostItem.js
  src/pages/Profile/ProfilePage.js
Labels: feat

#109 refactor: formCodeRefactoring
  src/component/form/AuthForm.js
  src/component/form/ProfileForm.js
Labels: refactor

#111 feat: comment box 스타일링
  src/component/common/CommentBox.js
  src/component/post/PostDetailComment.js
  src/pages/Post/PostDetailPage.js
Labels: feat

#113 Feat: postdetail
  src/component/post/CommentItem.js
  src/component/post/PostDetailContent.js
  src/component/post/UploadButton.js
  src/pages/Post/PostDetailPage.js
  src/pages/Post/PostUploadPage.js
Labels: feat, fix

#115 Style/modal
  src/App.js
  src/component/feed/Feed.js
  src/component/modal/ConfirmModal.js
  src/component/modal/PostItemModal.js
  src/component/modal/ProductModal.js
  src/component/modal/ProfileModal.js
  src/component/modal/modal.css
  src/component/post/PostItem.js
  src/component/post/PostList.js
  src/component/product/ProductItem.js
  src/component/user/UserProfile.js
  src/pages/Profile/ProfilePage.js
Labels: style

#117 feat: 상품폼 벨리데이션
  src/component/form/ProductForm.js
  src/lib/utils/productValidation.js
  src/pages/Product/ProductEditPage.js
  src/pages/Product/ProductUploadPage.js
Labels: feat

#126 Feat/profilestyled
  src/App.js
  src/assets/icons/yourProfile_chat.png
  src/component/common/Button.js
  src/component/common/ButtonBig.js
  src/component/common/ProfileInfo.js
  src/component/follow/FollowButton.js
  src/component/product/ProductList.js
  src/component/user/UserProfile.js
  src/lib/styles/palette.js
  src/pages/Profile/ProfilePage.js
Labels: feat, style

#127 feat: Splash+LoginPage스타일
  src/component/login/SocialLoginBtn.js
  src/lib/styles/GlobalStyle.js
  src/pages/Home/Splash.js
  src/pages/Login/LoginPage.js
Labels: feat

#128 feat: GlobalStyle에 input 리셋 추가
  src/lib/styles/GlobalStyle.js
Labels: feat

#131 style: productpage 스타일링
  src/pages/Product/ProductEditPage.js
Labels: feat

#130 style: 상품 폼 스타일링
  src/assets/icons/img-button.png
  src/component/common/ProfileInfo.js
  src/component/form/ProductForm.js
  src/component/user/UserProfile.js
  src/pages/Product/ProductUploadPage.js
  src/pages/Profile/ProfilePage.js
Labels: feat

#132 Feat/login+register
  src/assets/logo/Facebook_Logo.png
  src/assets/logo/Google_Logo.png
  src/assets/logo/Kakao_Logo.png
  src/component/common/ButtonRectangle.js
  src/component/form/AuthForm.js
  src/lib/styles/GlobalStyle.js
  src/pages/Home/HomePage.js
  src/pages/Login/LoginByEmail.js
  src/pages/Register/Register.js
Labels: feat

#134 style: 새로운 컨벤션에 따라 common폴더 내 컴포넌트명 수정
  eslintrc
  src/component/common/BackButton.js
  src/component/common/Button.js
  src/component/common/ButtonBig.js
  src/component/common/ButtonRectangle.js
  src/component/common/ButtonSmall.js
  src/component/common/CommentBox.js
  src/component/common/Header.js
  src/component/common/ImgUploadButton.js
  src/component/common/ModalButton.js
  src/component/common/NavBar.js
  src/component/common/ProfileInfo.js
  src/component/common/SearchButton.js
Labels: style

#135 Style/login compo name
  src/App.js
  src/component/common/CommentBox.js
  src/component/common/ImgUploadButton.js
  src/component/common/NavBar.js
  src/component/common/ProfileInfo.js
  src/component/login/SocialLoginBtn.js
  src/component/post/HeartButton.js
  src/component/post/PostItem.js
  src/lib/apis/heartApis.js
  src/lib/styles/globalStyle.js
  src/pages/Home/HomePage.js
  src/pages/Home/Splash.js
  src/pages/Login/LoginByEmail.js
  src/pages/Login/LoginPage.js
  src/pages/Register/Register.js
  src/pages/Search/SearchPage.js
Labels: style, rename

#137 Style: 팔로우 팔로잉 페이지 스타일링
  src/component/common/BackButton.js
  src/component/common/ButtonSmall.js
  src/component/common/Header.js
  src/component/follow/FollowButton.js
  src/component/follow/FollowContents.js
  src/component/follow/FollowUser.js
  src/component/user/UserProfile.js
  src/lib/apis/followApis.js
  src/lib/styles/palette.js
  src/pages/Follow/FollowerPage.js
  src/pages/Follow/FollowingPage.js
  src/pages/Home/HomePage.js
  src/pages/Profile/ProfilePage.js
Labels: style

#139 refactor: login 파트 파일 복구+리팩 진행
  src/component/form/AuthForm.js
  src/pages/Login/LoginPage.js
  src/pages/Register/Register.js
Labels: fix, refactor

#144 style: common 폴더 내 수정 코드 복원
  src/component/common/BackButton.js
  src/component/common/ButtonSmall.js
Labels: style

#138 style: form 스타일링
  .eslintrc
  src/assets/image/product_empty_img.png
  src/component/common/NavBar.js
  src/component/form/ProductForm.js
  src/component/post/PostList.js
  src/component/post/PostPicture.js
  src/component/product/ProductList.js
  src/pages/Product/ProductUploadPage.js
  src/pages/Profile/ProfilePage.js
Labels: feat

#143 feat: homePage 기본 스타일 적용
  src/component/common/SearchButton.js
  src/component/feed/Feed.js
Labels: feat

#140 feat: profile페이지와 profile폼 스타일
  src/component/form/AuthForm.js
  src/component/form/ProfileForm.js
Labels: feat

#145 feat: searchPage 스타일
  src/component/search/SearchResult.js
  src/pages/Search/SearchPage.js
Labels: feat

#146 fix/Common-setting 파일들 추가
  .eslintrc
  setting.json
Labels: fix

#152 feat: profileform 스타일 추가 수정
  src/component/common/ButtonBig.js
  src/component/form/ProfileForm.js
  src/pages/Profile/ProfilePage.js
  src/pages/Register/Register.js
Labels: feat

#154 feat: ProfileEditPage 스타일 완료
  src/component/form/ProfileForm.js
  src/pages/Profile/ProfileEditPage.js
Labels: feat

#156 Style: FollowButton.js 삭제
  src/component/common/ButtonBig.js
  src/component/common/ButtonSmall.js
  src/component/follow/FollowButton.js
  src/component/follow/FollowUser.js
  src/component/user/UserProfile.js
Labels: refactor, style, rename, remove

#165 Feat/search
  src/component/search/SearchResult.js
  src/component/search/SearchingItem.js
  src/component/search/SearchingResult.js
  src/lib/apis/searchApis.js
  src/pages/Search/SearchPage.js
Labels: feat

#166 Style/profilepage
  .eslintrc
  src/component/post/PostList.js
  src/component/product/ProductItem.js
  src/component/product/ProductList.js
  src/pages/Profile/ProfilePage.js
Labels: feat

#167 Fix/profileedit
  .prettierrc.js
  src/component/form/ProfileForm.js
  src/pages/Profile/ProfileEditPage.js
  src/pages/Profile/ProfilePage.js
Labels: fix

#159 Feat: chat
  src/component/chat/ChatItem.js
  src/pages/Chat/ChatListPage.js
  src/pages/Chat/ChatRoomPage.js
Labels: feat, refactor

#161 feat: 404페이지 스타일링
  src/pages/ErrorPage/Page404.js
Labels: feat

#169 fix: 검색어 없을 때 검색되는 에러 수정
  src/component/search/SearchingItem.js
  src/component/search/SearchingResult.js
  src/pages/Search/SearchPage.js
Labels: fix

#171 fix: emailvalid 오류 수정
  src/component/form/AuthForm.js
  src/pages/Register/Register.js
Labels: fix

#158 Feat: postupload
  src/component/post/UploadButton.js
  src/lib/apis/customAxios.js
  src/pages/Post/PostUploadPage.js
Labels: feat

#174 style: 프로필 팔로우 페이지 버튼 수정
  src.zip
  src/component/common/ButtonBig.js
  src/component/common/ButtonSmall.js
  src/component/post/HeartButton.js
  src/component/post/PostItem.js
Labels: style

#175 style: profilepage 스타일
  src/component/product/ProductItem.js
  src/component/product/ProductList.js
  src/pages/Profile/ProfilePage.js
Labels: feat

#178 style: profilepage 스타일링
  src/component/post/PostList.js
  src/component/product/ProductList.js
  src/component/user/UserProfile.js
  src/pages/Profile/ProfilePage.js
Labels: feat

#179 style: profilpage 스타일링
  src/component/post/PostList.js
  src/component/product/ProductList.js
Labels: feat

#180 style: button에 poiter 추가
  src/component/post/PostList.js
  src/component/product/ProductItem.js
Labels: feat

#181 feat/homepage 피드와 postitem 스타일
  src/component/feed/Feed.js
  src/component/post/HeartButton.js
  src/component/post/PostItem.js
  src/component/search/SearchingItem.js
  src/lib/styles/globalStyle.js
  src/pages/Home/HomePage.js
Labels: feat, fix

#183 feat: 검색어 글자색 바꾸기 기능
  src/component/search/SearchingItem.js
  src/component/search/SearchingResult.js
  src/lib/apis/searchApis.js
  src/pages/Search/SearchPage.js
Labels: feat

#191 feat: chat과 관련된 컴포넌트+페이지 리팩 완료
  src.zip
  src/assets/icons/chat_upload.png
  src/assets/image/camp.jpg
  src/assets/logo/ENFP.png
  src/assets/logo/INTJ.png
  src/assets/logo/ISTP.png
  src/component/chat/ChatItem.js
  src/component/chat/ChatList.js
  src/component/common/CommentBox copy.js
  src/component/post/CommentItem.js
  src/component/post/PostDetailComment.js
  src/component/post/PostDetailContent.js
  src/lib/dummy/chatdata.js
  src/pages/Chat/ChatListPage.js
  src/pages/Chat/ChatRoomPage.js
  src/pages/Post/PostDetailPage.js
  src/pages/Search/SearchPage.js
Labels: fix, refactor, style

#193 style: 하트버튼 수정
  src/assets/icons/heart.png
  src/assets/icons/heart_fill.png
  src/component/post/HeartButton.js
Labels: style

#195 Fix: comment
  src/component/common/CommentBox.js
  src/component/post/HeartButton.js
  src/component/post/PostDetailContent.js
  src/component/post/PostItem.js
Labels: feat

#196 Feat/ 로그인 여부 검사 및 토큰 유효성 검사
  src/App.js
  src/component/common/SearchButton.js
  src/component/context/LoginContext.js
  src/component/context/Provider.js
  src/component/feed/Feed.js
  src/lib/utils/isLogin.js
  src/lib/utils/isValidToken.js
  src/lib/utils/logout.js
  src/pages/ErrorPage/Page404.js
  src/pages/Home/HomePage.js
  src/pages/Home/Splash.js
  src/pages/Login/LoginByEmail.js
  src/pages/Login/LoginPage.js
  src/pages/Profile/ProfilePage.js
Labels: feat

#198 feat: postupload page 스타일
  src/assets/icons/404_logo.png
  src/assets/icons/basic_profile.png
  src/assets/icons/basic_profile_chat.png
  src/assets/icons/basic_profile_post.png
  src/assets/icons/chat_send.png
  src/assets/icons/heart.png
  src/assets/icons/heart_fill.png
  src/assets/icons/home.png
  src/assets/icons/home_fill.png
  src/assets/icons/icon_arrow_left.png
  src/assets/icons/icon_search.png
  src/assets/icons/img-button.png
  src/assets/icons/img_layers.png
  src/assets/icons/img_upload_post.png
  src/assets/icons/img_upload_profile.png
  src/assets/icons/message.png
  src/assets/icons/message_fill.png
  src/assets/icons/more_header.png
  src/assets/icons/more_post.png
  src/assets/icons/post-list-off.png
  src/assets/icons/post.png
  src/assets/icons/post_album.png
  src/assets/icons/post_album_fill.png
  src/assets/icons/post_fill.png
  src/assets/icons/post_list.png
  src/assets/icons/post_list_fill.png
  src/assets/icons/reple.png
  src/assets/icons/user.png
  src/assets/icons/user_fill.png
  src/assets/icons/x.png
  src/assets/icons/yourProfile_chat.png
  src/assets/icons/yourProfile_share.png
  src/component/common/Button.js
  src/component/common/ImgUploadButton.js
  src/component/follow/FollowContents.js
  src/component/follow/FollowUser.js
  src/component/form/ProductForm.js
  src/component/post/PostDetailContent.js
  src/component/post/PostItem.js
  src/component/product/ProductItem.js
  src/component/product/ProductList.js
  src/lib/apis/postApis.js
  src/lib/styles/globalStyle.js
  src/pages/Chat/ChatRoomPage.js
  src/pages/Post/PostDetailPage.js
  src/pages/Post/PostUploadPage.js
Labels: style

#199 fix: 스플레시 화면 스타일 오류 수정
  src/pages/Home/Splash.js
Labels: fix

#205 fix: 댓글 모달 수정
  src/component/post/CommentItem.js
Labels: fix

#208 Fix: post
  src/component/common/CommentBox.js
  src/component/common/ImgUploadButton.js
  src/component/post/PostDetailComment.js
  src/component/post/PostDetailContent.js
  src/component/post/UploadButton.js
  src/lib/apis/imageUploadApi.js
  src/pages/ErrorPage/Page404.js
  src/pages/Post/PostUploadPage.js
  src/pages/Profile/ProfileEditPage.js
Labels: fix

#207 feat: 404 버튼 변경
  src/component/common/SearchButton.js
  src/lib/apis/imageUploadApi.js
  src/lib/apis/registerApis.js
  src/lib/apis/searchApis.js
  src/pages/ErrorPage/Page404.js
Labels: feat

#209 fix: img 이름 수정
  src/component/form/ProductForm.js
  src/pages/Login/LoginByEmail.js
  src/pages/Product/ProductUploadPage.js
Labels: fix

#210 Feat/profile
  src/component/common/ButtonBig.js
  src/component/form/ProductForm.js
  src/component/post/PostDetailContent.js
  src/component/post/PostList.js
  src/component/product/ProductItem.js
  src/component/product/ProductList.js
  src/component/user/UserProfile.js
  src/pages/Chat/ChatRoomPage.js
  src/pages/Post/PostUploadPage.js
  src/pages/Product/ProductUploadPage.js
  src/pages/Profile/ProfilePage.js
Labels: refactor, style

#212 feat: 좋아요 버튼 유지
  src/component/post/HeartButton.js
  src/component/post/PostDetailContent.js
  src/component/post/PostItem.js
  src/component/post/PostList.js
Labels: feat

#215 Fix: comment
  src/component/common/CommentBox.js
  src/component/post/CommentItem.js
  src/component/post/PostDetailComment.js
  src/pages/Post/PostDetailPage.js
Labels: feat

#216 feat: 에러 이미지 처리
  src/assets/icons/error_alt_img.png
  src/component/common/CommentBox.js
  src/component/post/CommentItem.js
  src/component/post/PostDetailComment.js
  src/component/post/PostDetailContent.js
  src/component/post/PostItem.js
  src/component/product/ProductItem.js
  src/component/search/SearchingItem.js
  src/component/user/UserProfile.js
  src/pages/Post/PostDetailPage.js
Labels: feat

#218 fix: 오타 수정
  src/component/post/PostDetailComment.js
  src/component/post/PostDetailContent.js
Labels: fix

#219 fix: post 풀 이미지 보이기
  src/component/common/CommentBox.js
  src/component/post/PostDetailComment.js
  src/component/post/PostDetailContent.js
  src/component/post/PostItem.js
  src/pages/Search/SearchPage.js
Labels: fix

#220 feat: 에러 이미지 처리
  src/component/follow/FollowUser.js
  src/pages/Follow/FollowerPage.js
  src/pages/Follow/FollowingPage.js
Labels: feat

#221 fix: 포스트 디테일 페이지 댓글 버튼 링크 이동되게 수정
  src/component/post/CommentItem.js
  src/component/post/PostDetailComment.js
  src/component/post/PostDetailContent.js
Labels: feat, fix

#225 feat: token 없을때 interceptors 설정
  .eslintrc
  src/lib/apis/customAxios.js
Labels: feat

#223 fix: 이미지 안넣었을때 에러 처리
  src/component/post/PostItem.js
Labels: fix

#227 fix: 머지할때 발생한 오류 수정
  src/component/common/CommentBox.js
  src/component/post/PostDetailComment.js
  src/pages/Post/PostDetailPage.js
Labels: fix

#228 fix: 댓글 렌더링 오류 수정
  src/component/common/CommentBox.js
  src/component/post/CommentItem.js
  src/component/post/PostDetailComment.js
  src/pages/Post/PostDetailPage.js
Labels: fix

#234 refactor: authform, register 페이지 리펙토링
  src/App.js
  src/component/context/AppProvider.js
  src/component/form/AuthForm.js
  src/component/form/ProfileForm.js
  src/pages/Home/HomePage.js
  src/pages/Login/LoginByEmail.js
  src/pages/Register/Register.js
Labels: refactor

#235 refactor: 회원가입 및 로그인 리펙토링
  src/component/form/AuthForm.js
  src/component/form/ProfileForm.js
  src/pages/Login/LoginByEmail.js
  src/pages/Register/Register.js
Labels: refactor

#239 fix: 모바일 화면 네브 테스트
  src/component/common/NavBar.js
Labels: fix

#230 fix: 스타일 오류 수정
  package-lock.json
  package.json
  src/App.js
  src/component/form/AuthForm.js
  src/component/post/PostList.js
  src/lib/styles/globalStyle.js
Labels: fix

#241 refactor: 회원가입 벨리데이션 리펙토링
  src/component/form/ProfileForm.js
  src/lib/utils/loginValidation.js
  src/lib/utils/profileValidation.js
  src/lib/utils/registerValidation.js
  src/pages/Register/Register.js
Labels: refactor

#236 Feat: comment
  src/component/common/CommentBox.js
  src/component/post/CommentItem.js
  src/lib/utils/timeConverter.js
Labels: feat

#244 feat:error 이미지 교체
  src/assets/image/post_alt_img.png
  src/assets/image/product_alt_img.png
  src/component/post/PostDetailContent.js
  src/component/post/PostItem.js
  src/component/product/ProductItem.js
Labels: feat

#242 refactor: LoginByEmail페이지 코드 보완
  src/pages/Login/LoginByEmail.js
Labels: refactor

#245 Feat: footer
  src/assets/logo/CAMPERZ.png
  src/assets/logo/github.png
  src/component/common/Footer.js
  src/component/post/PostDetailComment.js
  src/pages/Post/PostDetailPage.js
  src/pages/Profile/ProfilePage.js
Labels: feat

#248 Feat/footer
  src/component/common/Footer.js
  src/pages/Chat/ChatListPage.js
  src/pages/Home/HomePage.js
  src/pages/Post/PostDetailPage.js
  src/pages/Profile/ProfilePage.js
Labels: feat, fix

#246 fix: 네브바, 코멘트박스 고정
  src/component/common/CommentBox.js
  src/component/common/NavBar.js
Labels: fix

#251 fix: 코멘트박스 하단 고정 후 채팅화면 잘리는 문제 보정
  .editorconfig
  src/component/common/CommentBox.js
  src/pages/Chat/ChatRoomPage.js
Labels: fix

#249 feat: 배경 컴포넌트 구현
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/assets/icons/arrow.png
  src/component/background/Background.js
  src/pages/Chat/ChatListPage.js
  src/pages/Chat/ChatRoomPage.js
  src/pages/Post/PostDetailPage.js
Labels: feat

#253 Feat: 날씨기능 구현
  src/assets/icons/Ellipse.png
  src/assets/icons/cloud.png
  src/assets/icons/cloud_thunder.png
  src/assets/icons/doublecloud.png
  src/assets/icons/hazzy.png
  src/assets/icons/partly_cloudy_day.png
  src/assets/icons/rainy.png
  src/assets/icons/rainy_day.png
  src/assets/icons/snow.png
  src/assets/icons/sunny.png
  src/assets/icons/sunrise.png
  src/assets/icons/sunset.png
  src/component/chat/WeatherContents.js
  src/pages/Chat/ChatListPage.js
Labels: feat, style

#255 refactor: 버튼 엑티브 방식 수정
  src/component/common/Button.js
  src/component/common/Footer.js
  src/component/common/Header.js
  src/component/form/ProductForm.js
  src/component/post/PostItem.js
  src/component/product/ProductItem.js
  src/component/product/ProductList.js
  src/lib/utils/productValidation.js
  src/pages/Product/ProductEditPage.js
  src/pages/Profile/ProfileEditPage.js
Labels: refactor

#257 fix: 댓글 새로 달리는 위치 수정
  src/component/common/CommentBox.js
  src/component/post/CommentItem.js
  src/component/post/PostDetailComment.js
Labels: fix

#254 fix: 채팅 페이지 내 footer 위치 수정
  src/pages/Chat/ChatListPage.js
  src/pages/Post/PostDetailPage.js
Labels: fix

#258 fix: 모달 z-index추가
  public/index.html
  src/App.js
  src/component/modal/modal.css
Labels: fix

#260 Fix/layout
  src/lib/styles/globalStyle.js
  src/pages/Chat/ChatListPage.js
  src/pages/Home/HomePage.js
  src/pages/Post/PostDetailPage.js
  src/pages/Profile/ProfilePage.js
Labels: fix

#261 fix: 긴댓글 작성시 이상해 지는 문제 해결
  src/component/post/CommentItem.js
  src/component/post/PostDetailComment.js
Labels: fix

#262 fix: 코멘트 레이아웃 수정
  src/App.js
  src/component/post/CommentItem.js
Labels: style

#263 fix: 포스트 레이아웃 오른쪽 마진 추가
  src/component/post/PostDetailContent.js
  src/component/post/PostItem.js
Labels: fix

#264 style: 백그라운드 스타일 추가
  src/component/background/Background.js
Labels: style

#266 refactor: weather 현재위치 수정
  src/component/chat/WeatherContents.js
Labels: refactor
