Repository 20th-lion/camperz, pull requests merged in 2023-01, with the labels that each got.

#268 feat: 로딩 화면 구현
  src/App.js
  src/assets/image/spinner.gif
  src/component/chat/WeatherContents.js
  src/component/context/AppProvider.js
  src/component/product/ProductItem.js
  src/component/user/UserProfile.js
  src/lib/apis/customAxios.js
  src/lib/styles/globalStyle.js
  src/lib/utils/isValidToken.js
Labels: feat

#269 feat: 로딩 조건 추가
  src/component/form/AuthForm.js
  src/lib/apis/customAxios.js
Labels: feat

#271 refactor: 색 팔레트 코드 헥사코드로 바꾸기
  src/component/common/Button.js
  src/component/common/ButtonBig.js
  src/component/common/ButtonRectangle.js
  src/component/common/ButtonSmall.js
  src/component/common/CommentBox.js
  src/component/user/UserProfile.js
  src/lib/styles/palette.js
Labels: refactor

#273 Feat: 날씨 위치정보 에러처리 화면구현
  src/assets/icons/ErrLocation.png
  src/component/chat/WeatherContents.js
Labels: feat, style

#274 fix: 색 변환 실수 수정
  src/component/common/Button.js
  src/component/common/ButtonBig.js
  src/component/common/ButtonRectangle.js
  src/component/common/ButtonSmall.js
  src/component/common/CommentBox.js
Labels: fix

#275 fix: 벨리데이션 오류 수정
  src/component/form/AuthForm.js
Labels: fix

#276 fix: 사진만 보기 에러이미지 처리
  src/component/post/PostPicture.js
  src/lib/apis/customAxios.js
  src/lib/apis/imageUploadApi.js
  src/pages/Product/ProductEditPage.js
  src/pages/Product/ProductUploadPage.js
  src/pages/Profile/ProfileEditPage.js
  src/pages/Register/Register.js
Labels: fix

#278 fix: 사진만 보기 에러 이미지 처리
  src/component/post/PostPicture.js
Labels: fix

#280 Fix: 게시물 수정 오류
  src/component/post/UploadButton.js
  src/pages/Post/PostUploadPage.js
Labels: fix, style
